[package]
name = "pbrrr"
version = "0.1.0"
authors = ["Manish Mathai <manishpmathai@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
fern = "0.6"
chrono = "0.4"
clap = "~2.33"
